# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello/hello.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("hello/hello.proto", :syntax => :proto3) do
    add_message "hello.HelloRequest" do
      optional :name, :string, 1
    end
    add_message "hello.HelloReply" do
      optional :message, :string, 1
    end
  end
end

module Hello
  HelloRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.HelloRequest").msgclass
  HelloReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.HelloReply").msgclass
end
