# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: hello/hello.proto for package 'hello'

require 'grpc'
require './hello/hello_pb'

module Hello
  module Greeter
    # サービスをささっと定義する
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'hello.Greeter'

      # HelloRequestを受け取ったらHelloReplyを返すそれをSayHelloとする
      rpc :SayHello, HelloRequest, HelloReply
    end

    Stub = Service.rpc_stub_class
  end
end
